// Durées de conservation indicatives (jours), clés = nom de produit normalisé
// (minuscules, sans accents). Valeurs issues de sources grand public
// (Que Choisir, ANSES/gouv, blogs spécialisés) — ordres de grandeur typiques
// pour une conservation au frais quand c'est pertinent.
//   shelfLifeDays      : durée typique avant péremption (à l'achat)
//   afterOpenDays      : durée max après ouverture (null = non pertinent)

export type Conservation = { shelfLifeDays: number; afterOpenDays: number | null };

export const CONSERVATION: Record<string, Conservation> = {
  // ── Fruits & Légumes (frais) ───────────────────────────────────────
  "pommes": { shelfLifeDays: 30, afterOpenDays: null },
  "bananes": { shelfLifeDays: 6, afterOpenDays: null },
  "oranges": { shelfLifeDays: 20, afterOpenDays: null },
  "citrons": { shelfLifeDays: 21, afterOpenDays: null },
  "fraises": { shelfLifeDays: 3, afterOpenDays: null },
  "tomates": { shelfLifeDays: 7, afterOpenDays: null },
  "carottes": { shelfLifeDays: 21, afterOpenDays: null },
  "oignons": { shelfLifeDays: 60, afterOpenDays: null },
  "ail": { shelfLifeDays: 90, afterOpenDays: null },
  "pommes de terre": { shelfLifeDays: 30, afterOpenDays: null },
  "courgettes": { shelfLifeDays: 7, afterOpenDays: null },
  "aubergines": { shelfLifeDays: 7, afterOpenDays: null },
  "poivrons": { shelfLifeDays: 10, afterOpenDays: null },
  "concombre": { shelfLifeDays: 7, afterOpenDays: null },
  "salade": { shelfLifeDays: 5, afterOpenDays: null },
  "champignons": { shelfLifeDays: 5, afterOpenDays: null },
  "brocoli": { shelfLifeDays: 7, afterOpenDays: null },
  "haricots verts": { shelfLifeDays: 5, afterOpenDays: null },
  "petits pois": { shelfLifeDays: 3, afterOpenDays: null },
  "epinards": { shelfLifeDays: 4, afterOpenDays: null },
  "avocat": { shelfLifeDays: 5, afterOpenDays: null },
  "mangue": { shelfLifeDays: 6, afterOpenDays: null },
  "ananas": { shelfLifeDays: 5, afterOpenDays: null },
  "poireaux": { shelfLifeDays: 10, afterOpenDays: null },
  "chou": { shelfLifeDays: 14, afterOpenDays: null },
  "echalotes": { shelfLifeDays: 60, afterOpenDays: null },
  "gingembre": { shelfLifeDays: 21, afterOpenDays: null },
  "celeri": { shelfLifeDays: 10, afterOpenDays: null },
  "betteraves": { shelfLifeDays: 21, afterOpenDays: null },
  "radis": { shelfLifeDays: 7, afterOpenDays: null },
  "coriandre fraiche": { shelfLifeDays: 5, afterOpenDays: null },
  "persil frais": { shelfLifeDays: 5, afterOpenDays: null },
  "menthe fraiche": { shelfLifeDays: 5, afterOpenDays: null },

  // ── Viandes & Poissons (frais) ─────────────────────────────────────
  "poulet (filets)": { shelfLifeDays: 2, afterOpenDays: null },
  "poulet (entier)": { shelfLifeDays: 2, afterOpenDays: null },
  "steak hache": { shelfLifeDays: 1, afterOpenDays: null },
  "boeuf (bavette)": { shelfLifeDays: 4, afterOpenDays: null },
  "porc (cotes)": { shelfLifeDays: 4, afterOpenDays: null },
  "porc (echine)": { shelfLifeDays: 4, afterOpenDays: null },
  "agneau": { shelfLifeDays: 4, afterOpenDays: null },
  "dinde": { shelfLifeDays: 2, afterOpenDays: null },
  "saumon": { shelfLifeDays: 2, afterOpenDays: null },
  "cabillaud": { shelfLifeDays: 2, afterOpenDays: null },
  "thon (frais)": { shelfLifeDays: 2, afterOpenDays: null },
  "crevettes": { shelfLifeDays: 2, afterOpenDays: null },
  "merguez": { shelfLifeDays: 3, afterOpenDays: null },
  "saucisses": { shelfLifeDays: 3, afterOpenDays: null },
  "lardons": { shelfLifeDays: 7, afterOpenDays: 3 },
  "jambon": { shelfLifeDays: 7, afterOpenDays: 3 },

  // ── Produits laitiers ──────────────────────────────────────────────
  "lait": { shelfLifeDays: 60, afterOpenDays: 4 },
  "lait d'amande": { shelfLifeDays: 180, afterOpenDays: 5 },
  "lait de coco": { shelfLifeDays: 365, afterOpenDays: 4 },
  "beurre": { shelfLifeDays: 60, afterOpenDays: 30 },
  "yaourts nature": { shelfLifeDays: 21, afterOpenDays: null },
  "fromage blanc": { shelfLifeDays: 21, afterOpenDays: 7 },
  "creme fraiche": { shelfLifeDays: 21, afterOpenDays: 4 },
  "creme liquide": { shelfLifeDays: 30, afterOpenDays: 4 },
  "mascarpone": { shelfLifeDays: 21, afterOpenDays: 3 },
  "ricotta": { shelfLifeDays: 14, afterOpenDays: 3 },
  "mozzarella": { shelfLifeDays: 14, afterOpenDays: 3 },
  "parmesan": { shelfLifeDays: 90, afterOpenDays: 30 },
  "comte": { shelfLifeDays: 60, afterOpenDays: 21 },
  "camembert": { shelfLifeDays: 21, afterOpenDays: 7 },
  "chevre frais": { shelfLifeDays: 14, afterOpenDays: 5 },
  "fromage rape": { shelfLifeDays: 30, afterOpenDays: 7 },
  "oeufs": { shelfLifeDays: 28, afterOpenDays: null },

  // ── Boulangerie ────────────────────────────────────────────────────
  "baguette": { shelfLifeDays: 2, afterOpenDays: null },
  "pain de mie": { shelfLifeDays: 7, afterOpenDays: 7 },
  "pain complet": { shelfLifeDays: 4, afterOpenDays: null },
  "pain burger": { shelfLifeDays: 7, afterOpenDays: null },
  "brioche": { shelfLifeDays: 7, afterOpenDays: null },
  "croissants": { shelfLifeDays: 2, afterOpenDays: null },
  "biscottes": { shelfLifeDays: 120, afterOpenDays: 21 },
  "chapelure": { shelfLifeDays: 180, afterOpenDays: 60 },
  "wraps/tortillas": { shelfLifeDays: 30, afterOpenDays: 7 },

  // ── Épicerie (placard) + après ouverture pour bocaux/conserves ─────
  "pates": { shelfLifeDays: 730, afterOpenDays: null },
  "nouilles chinoises": { shelfLifeDays: 365, afterOpenDays: null },
  "riz": { shelfLifeDays: 730, afterOpenDays: null },
  "semoule": { shelfLifeDays: 730, afterOpenDays: null },
  "farine": { shelfLifeDays: 365, afterOpenDays: null },
  "maizena": { shelfLifeDays: 730, afterOpenDays: null },
  "sucre": { shelfLifeDays: 1095, afterOpenDays: null },
  "sel": { shelfLifeDays: 3650, afterOpenDays: null },
  "levure": { shelfLifeDays: 365, afterOpenDays: null },
  "lentilles": { shelfLifeDays: 730, afterOpenDays: null },
  "pois chiches": { shelfLifeDays: 730, afterOpenDays: null },
  "haricots rouges": { shelfLifeDays: 730, afterOpenDays: 3 },
  "conserves de mais": { shelfLifeDays: 1095, afterOpenDays: 3 },
  "conserves de thon": { shelfLifeDays: 1095, afterOpenDays: 2 },
  "olives": { shelfLifeDays: 365, afterOpenDays: 14 },
  "huile d'olive": { shelfLifeDays: 540, afterOpenDays: 60 },
  "huile tournesol": { shelfLifeDays: 365, afterOpenDays: 60 },
  "huile de sesame": { shelfLifeDays: 365, afterOpenDays: 60 },
  "sauce tomate": { shelfLifeDays: 365, afterOpenDays: 5 },
  "concentre de tomates": { shelfLifeDays: 365, afterOpenDays: 7 },
  "sauce soja": { shelfLifeDays: 730, afterOpenDays: 365 },
  "nuoc-mam": { shelfLifeDays: 730, afterOpenDays: 365 },
  "pate de curry": { shelfLifeDays: 365, afterOpenDays: 30 },
  "confiture": { shelfLifeDays: 365, afterOpenDays: 30 },
  "miel": { shelfLifeDays: 1825, afterOpenDays: null },
  "moutarde": { shelfLifeDays: 365, afterOpenDays: 60 },
  "ketchup": { shelfLifeDays: 365, afterOpenDays: 30 },
  "mayonnaise": { shelfLifeDays: 180, afterOpenDays: 14 },
  "vinaigre": { shelfLifeDays: 1095, afterOpenDays: null },
  "vinaigre balsamique": { shelfLifeDays: 1095, afterOpenDays: null },
  "cafe": { shelfLifeDays: 365, afterOpenDays: 30 },
  "cafe moulu": { shelfLifeDays: 365, afterOpenDays: 30 },
  "the": { shelfLifeDays: 730, afterOpenDays: null },
  "chocolat": { shelfLifeDays: 365, afterOpenDays: null },
  "bouillon cube": { shelfLifeDays: 540, afterOpenDays: null },
  "pate brisee": { shelfLifeDays: 30, afterOpenDays: null },
  "pate feuilletee": { shelfLifeDays: 30, afterOpenDays: null },

  // ── Surgelés ───────────────────────────────────────────────────────
  "frites": { shelfLifeDays: 365, afterOpenDays: null },
  "glaces": { shelfLifeDays: 365, afterOpenDays: null },
  "pizza surgelee": { shelfLifeDays: 365, afterOpenDays: null },
  "nuggets": { shelfLifeDays: 365, afterOpenDays: null },
  "legumes surgeles": { shelfLifeDays: 365, afterOpenDays: null },
  "fruits surgeles": { shelfLifeDays: 365, afterOpenDays: null },
  "poisson pane": { shelfLifeDays: 365, afterOpenDays: null },
  "epinards surgeles": { shelfLifeDays: 365, afterOpenDays: null },

  // ── Boissons ───────────────────────────────────────────────────────
  "jus d'orange": { shelfLifeDays: 30, afterOpenDays: 4 },
  "coca-cola": { shelfLifeDays: 270, afterOpenDays: 3 },
  "eau plate": { shelfLifeDays: 365, afterOpenDays: null },
  "eau gazeuse": { shelfLifeDays: 365, afterOpenDays: 2 },
  "biere": { shelfLifeDays: 270, afterOpenDays: null },
  "vin blanc": { shelfLifeDays: 1095, afterOpenDays: 3 },
  "vin rouge": { shelfLifeDays: 1095, afterOpenDays: 3 },
  "sirop": { shelfLifeDays: 540, afterOpenDays: 90 },
};
